services:
  - type: web
    name: mycardsite-backend
    region: frankfurt
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
    runtime: python

databases:
  - name: mycardsite-db
    region: frankfurt
    plan: free