services:
  - type: web
    name: mycardsite-backend
    region: frankfurt
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://my-default-site-6batv4x79-remodiks-projects.vercel.app
      - key: WAKATIME_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: dev@remod3.ru
      - key: PYTHON_VERSION
        value: "3.11.0"
    runtime: python

databases:
  - name: mycardsite-db
    region: frankfurt
    plan: free