services:
  - type: web
    name: mycardsite-backend
    region: frankfurt
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://remod3.ru
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: dev@remod3.ru
      - key: PYTHON_VERSION
        value: "3.11.0"
    runtime: python